# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           ripgrep-edit
Version:        0.2.8
Release:        %autorelease
Summary:        Edit ripgrep search results across multiple files

License:        GPL-3.0-or-later OR AGPL-3.0-or-later

URL:            https://gitlab.com/aarcange/ripgrep-edit
Source:         %name-%version.tar.gz

BuildRequires:  cargo-rpm-macros >= 26 ripgrep
Requires: ripgrep

%global _description %{expand:
Edit ripgrep search results across multiple files.}

%description %{_description}

%prep
%autosetup -n ripgrep-edit-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
mkdir -p %{buildroot}%{_datarootdir}/%{name}
cp -a emacs %{buildroot}%{_datarootdir}/%{name}

%if %{with check}
%check
%cargo_test
%endif

%files
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/rg-edit
%{_datarootdir}/%{name}

%changelog
%autochangelog
